openapi: 3.0.2
info:
  title: Web Server API
  version: '1.0'
  description: This API provides details of communication between SAMAS and external event servers.
  contact:
    name: Matrix Comsec Pvt. Ltd.
  x-logo:
    url: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /Token:
    description: To get the JWT Token from Server.
    get:
      tags: []
      operationId: GetGetToken
      description: To get the JW token from server.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: JWToken
                type: object
                properties:
                  token:
                    type: string
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Method Not Allowed
        '500':
          description: Internal Server Error
      security:
        - Basic Auth: []
    x-last-modified: 1610526467320
    parameters: []
  /SendEvent:
    post:
      requestBody:
        description: Event details will be send in Body.
        required: true
        content:
          application/json:
            schema:
              title: Event
              description: ''
              required:
                - eventcode
                - eventname
                - Datetime
                - eventseverity
                - containsimage
              type: object
              properties:
                eventcode:
                  type: number
                eventname:
                  type: string
                Datetime:
                  format: date-time
                  type: string
                eventseverity:
                  maximum: 4
                  minimum: 1
                  enum:
                    - 1
                    - 2
                    - 3
                    - 4
                  type: number
                containsimage:
                  type: boolean
                AdditionalData:
                  title: AdditionalData Structure
                  type: object
                  properties:
                    Field1:
                      type: string
                    Field2:
                      type: string
                    Field3:
                      type: string
                    Field4:
                      type: string
                    Field5:
                      type: string
                    Field6:
                      type: string
                    Field7:
                      type: string
                    Field8:
                      type: string
                    Field9:
                      type: string
                    Field10:
                      type: string
                    Field11:
                      type: string
                    Field12:
                      type: string
                    Field13:
                      type: string
                    Field14:
                      type: string
                    Field15:
                      type: string
                    Field16:
                      type: string
                    Field17:
                      type: string
                    Field18:
                      type: string
                    Field19:
                      type: string
                    Field20:
                      type: string
                  x-examples:
                    User Detected Event Additional Data:
                      Field1: garvit
                      Field2: 'R & D'
                      Field3: Garvit Chugh
                      Field4: '50'
                      Field5: '23'
                      Field6: Male
              x-examples: {}
          application/xml:
            schema:
              title: Event
              description: ''
              required:
                - eventcode
                - eventname
                - Datetime
                - eventseverity
                - containsimage
              type: object
              properties:
                eventcode:
                  type: number
                eventname:
                  type: string
                Datetime:
                  format: date-time
                  type: string
                eventseverity:
                  maximum: 4
                  minimum: 1
                  enum:
                    - 1
                    - 2
                    - 3
                    - 4
                  type: number
                containsimage:
                  type: boolean
                AdditionalData:
                  title: AdditionalData Structure
                  type: object
                  properties:
                    Field1:
                      type: string
                    Field2:
                      type: string
                    Field3:
                      type: string
                    Field4:
                      type: string
                    Field5:
                      type: string
                    Field6:
                      type: string
                    Field7:
                      type: string
                    Field8:
                      type: string
                    Field9:
                      type: string
                    Field10:
                      type: string
                    Field11:
                      type: string
                    Field12:
                      type: string
                    Field13:
                      type: string
                    Field14:
                      type: string
                    Field15:
                      type: string
                    Field16:
                      type: string
                    Field17:
                      type: string
                    Field18:
                      type: string
                    Field19:
                      type: string
                    Field20:
                      type: string
                  x-examples:
                    User Detected Event Additional Data:
                      Field1: garvit
                      Field2: 'R & D'
                      Field3: Garvit Chugh
                      Field4: '50'
                      Field5: '23'
                      Field6: Male
              x-examples: {}
      tags:
        - Event Data
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: OK
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '405':
          description: Method Not Allowed
        '500':
          content:
            application/json:
              schema:
                enum:
                  - 'Invalid value in <ParaName>'
                  - 'Mandatory parameter <ParaName> missing>'
                type: string
          description: Internal Server Error
      security:
        - JWTAUTH: []
      operationId: post-SendEvent
      summary: SendEvent
      description: This API is used for sending 3rd Party events to SAMAS.
    description: To send the event data to SAMAS Server.
    x-last-modified: 1610527256920
components:
  schemas:
    Event:
      title: Event
      description: ''
      required:
        - eventcode
        - eventname
        - Datetime
        - eventseverity
        - containsimage
      type: object
      properties:
        eventcode:
          type: number
        eventname:
          type: string
        Datetime:
          format: date-time
          type: string
        eventseverity:
          maximum: 4
          minimum: 1
          enum:
            - 1
            - 2
            - 3
            - 4
          type: number
        containsimage:
          type: boolean
        AdditionalData:
          title: AdditionalData Structure
          type: object
          properties:
            Field1:
              type: string
            Field2:
              type: string
            Field3:
              type: string
            Field4:
              type: string
            Field5:
              type: string
            Field6:
              type: string
            Field7:
              type: string
            Field8:
              type: string
            Field9:
              type: string
            Field10:
              type: string
            Field11:
              type: string
            Field12:
              type: string
            Field13:
              type: string
            Field14:
              type: string
            Field15:
              type: string
            Field16:
              type: string
            Field17:
              type: string
            Field18:
              type: string
            Field19:
              type: string
            Field20:
              type: string
          x-examples:
            User Detected Event Additional Data:
              Field1: garvit
              Field2: 'R & D'
              Field3: Garvit Chugh
              Field4: '50'
              Field5: '23'
              Field6: Male
      x-examples: {}
    JWToken:
      title: JWToken
      type: object
      properties:
        token:
          type: string
  securitySchemes:
    Basic Auth:
      type: http
      scheme: Basic
      x-last-modified: 1610526414594
      description: ''
    JWTAUTH:
      type: http
      scheme: bearer
  responses: {}
  parameters: {}
  requestBodies:
    SendEvent Request Body:
      name: ''
      required: false
      content:
        application/json:
          example: ''
          schema:
            title: Event
            description: ''
            required:
              - eventcode
              - eventname
              - Datetime
              - eventseverity
              - containsimage
            type: object
            properties:
              eventcode:
                type: number
              eventname:
                type: string
              Datetime:
                format: date-time
                type: string
              eventseverity:
                maximum: 4
                minimum: 1
                enum:
                  - 1
                  - 2
                  - 3
                  - 4
                type: number
              containsimage:
                type: boolean
              AdditionalData:
                title: AdditionalData Structure
                type: object
                properties:
                  Field1:
                    type: string
                  Field2:
                    type: string
                  Field3:
                    type: string
                  Field4:
                    type: string
                  Field5:
                    type: string
                  Field6:
                    type: string
                  Field7:
                    type: string
                  Field8:
                    type: string
                  Field9:
                    type: string
                  Field10:
                    type: string
                  Field11:
                    type: string
                  Field12:
                    type: string
                  Field13:
                    type: string
                  Field14:
                    type: string
                  Field15:
                    type: string
                  Field16:
                    type: string
                  Field17:
                    type: string
                  Field18:
                    type: string
                  Field19:
                    type: string
                  Field20:
                    type: string
                x-examples:
                  User Detected Event Additional Data:
                    Field1: garvit
                    Field2: 'R & D'
                    Field3: Garvit Chugh
                    Field4: '50'
                    Field5: '23'
                    Field6: Male
            x-examples: {}
          encoding: ''
      x-last-modified: 1610527398532
tags:
  - name: Event Data
    description: Used for sending data of an event
security: []
